export const allProducts = [
  {
    id: "1",
    name: "Tobacco plant with red flowers",
    desc: "Lorem ipsum seus ipsummm",
    price: 5000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "2",
    name: "Product 2",
    desc: "Lorem ipsum seus ipsummm",
    price: 4000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "3",
    name: "Product 3",
    desc: "Lorem ipsum seus ipsummm",
    price: 7000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "4",
    name: "Product 4",
    desc: "Lorem ipsum seus ipsummm",
    price: 3400,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "5",
    name: "Product 5",
    desc: "Lorem ipsum seus ipsummm",
    price: 3500,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "6",
    name: "Product 6",
    desc: "Lorem ipsum seus ipsummm",
    price: 5500,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "7",
    name: "Product 7",
    desc: "Lorem ipsum seus ipsummm",
    price: 2700,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "8",
    name: "Product 8",
    desc: "Lorem ipsum seus ipsummm",
    price: 3400,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "9",
    name: "Product 9",
    desc: "Lorem ipsum seus ipsummm",
    price: 5000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "10",
    name: "Product 10",
    desc: "Lorem ipsum seus ipsummm",
    price: 7000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "11",
    name: "Tobacco plant with red flowers",
    desc: "Lorem ipsum seus ipsummm",
    price: 6000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "12",
    name: "Product 2",
    desc: "Lorem ipsum seus ipsummm",
    price: 3000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "13",
    name: "Product 3",
    desc: "Lorem ipsum seus ipsummm",
    price: 4500,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "14",
    name: "Product 4",
    desc: "Lorem ipsum seus ipsummm",
    price: 5900,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "15",
    name: "Product 5",
    desc: "Lorem ipsum seus ipsummm",
    price: 8000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "16",
    name: "Product 6",
    desc: "Lorem ipsum seus ipsummm",
    price: 3400,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "17",
    name: "Product 7",
    desc: "Lorem ipsum seus ipsummm",
    price: 3200,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "18",
    name: "Product 8",
    desc: "Lorem ipsum seus ipsummm",
    price: 7000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "19",
    name: "Product 9",
    desc: "Lorem ipssum seus ipsummm",
    price: 5600,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "20",
    name: "Product 10",
    desc: "Lorem ipsum seus ipsummm",
    price: 4000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "21",
    name: "Tobacco plant",
    desc: "Lorem ipsum seus ipsummm",
    price: 6000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "22",
    name: "Product 2",
    desc: "Lorem ipsum seus ipsummm",
    price: 6000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "23",
    name: "Product 3",
    desc: "Lorem ipsum seus ipsummm",
    price: 6000,
    image: "https://via.placeholder.com/150",
  },
  {
    id: "24",
    name: "Product 4",
    desc: "Lorem ipsum seus ipsummm",
    price: 6000,
    image: "https://via.placeholder.com/150",
  },
];
